name: my_notes_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  google_sign_in: ^6.2.2
  go_router: ^14.8.1
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  google_fonts: ^6.2.1
  firebase_analytics: ^11.4.4
  intl: ^0.20.2
  pull_to_refresh_flutter3: ^2.0.2
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  flutter_platform_widgets: ^8.0.0
  animated_text_kit: ^4.2.3
  searchfield: ^1.2.4
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.2
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.4
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
